services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stock_portfolio
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/sql/test-data.sql:/docker-entrypoint-initdb.d/test-data.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  bff:
    build:
      context: .
      dockerfile: bff/Dockerfile
    ports:
      - "${BFF_PORT}:3000"
    env_file:
      - ./bff/.env.sample
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      # Mount files exactly where the imports expect them
      - ./bff/src:/app/src
      - ./db/models:/app/../../../db/models
      - ./db/repositories:/app/../../../db/repositories
      - ./db/prisma:/app/prisma

volumes:
  postgres_data:
