services:
  postgres:
    image: postgres:14
    networks:
      - stock-portfolio-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stock_portfolio
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/sql/all.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./db/sql/test-data.sql:/docker-entrypoint-initdb.d/2-data.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:21.1
    networks:
      - stock-portfolio-network
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/stock_portfolio
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KC_HEALTH_ENABLED: "true"
      KC_HTTP_RELATIVE_PATH: "/"
      KC_HOSTNAME: keycloak
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://keycloak:8080/health/ready"]
      interval: 15s
      timeout: 5s
      retries: 15

  bff:
    build:
      context: .
      dockerfile: bff/Dockerfile
    networks:
      - stock-portfolio-network
    ports:
      - "${BFF_PORT}:${INTERNAL_BFF_PORT}"
    env_file:
      - ./bff/.env.sample
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started
        #condition: service_healthy
    volumes:
      # Mount files exactly where the imports expect them
      - ./bff/src:/app/src
      - ./db/models:/app/../../../db/models
      - ./db/repositories:/app/../../../db/repositories
      - ./db/prisma:/app/prisma

networks:
  stock-portfolio-network:
    driver: bridge

volumes:
  postgres_data:
