-- *************** SqlDBM: PostgreSQL ****************;
-- ***************************************************;


-- ************************************** HOLDINGS

CREATE TABLE HOLDINGS
(
 HOLDINGS_ID  text NOT NULL,
 PORTFOLIOS_ID text NOT NULL,
 ISIN         text NOT NULL,
 QUANTITY     int NOT NULL,
 START_DATE   date NOT NULL,
 END_DATE     date NULL,
 CONSTRAINT PK_holdings PRIMARY KEY ( HOLDINGS_ID ),
 CONSTRAINT FK_18 FOREIGN KEY ( PORTFOLIOS_ID ) REFERENCES PORTFOLIOS ( PORTFOLIOS_ID ),
 CONSTRAINT FK_21 FOREIGN KEY ( ISIN ) REFERENCES STOCKS ( ISIN )
);

CREATE INDEX fkIdx_19 ON HOLDINGS
(
 PORTFOLIOS_ID
);

CREATE INDEX fkIdx_22 ON HOLDINGS
(
 ISIN
);